script_entry : ../src/backTrans.py
protein_sequences : "/home/brice/Desktop/work_PhD/projects/backTranslate/priv/5_rifins.fasta"
# protein_sequences : "/home/brice/Desktop/work_PhD/projects/backTranslate/priv/3d7_rifins/input_data/3D7_rifins.fasta"
results : "results"
params : {
    "backtrans_dists": [24, 26], 
    "backtrans_num_samples": [200, 400],
    "ensemble_dists": [28, 30]
}
